const dailyTips = [
    "Stay hydrated! Drink at least 2 liters of water daily for better energy and focus.",
    "Eat the rainbow! More colorful fruits and veggies mean more diverse nutrients.",
    "Chew slowly! Enjoy your food and help digestion by eating mindfully.",
    "Swap soda for infused water! Try lemon, mint, or berries for a fresh twist.",
    "Start your day with a high-protein breakfast to stay full longer.",
    "Limit processed foods! Go for whole, natural ingredients whenever possible.",
    "Take the stairs instead of the elevator for a quick health boost!",
    "Sleep at least 7-8 hours! Poor sleep can lead to weight gain and fatigue.",
    "Meal prep on Sundays! It helps save time and makes healthy eating easier.",
    "Snack on nuts! They’re packed with healthy fats and protein to keep you full.",
    "Try a new vegetable this week! Variety is key to a balanced diet.",
    "Cut back on sugar! Swap sugary snacks for fruits or dark chocolate.",
    "Get outside! Fresh air and sunlight improve mood and vitamin D levels.",
    "Eat more fiber! It keeps your gut happy and supports digestion.",
    "Practice gratitude daily! A positive mindset improves overall well-being.",
    "Move every hour! Stretch or walk for a minute to keep circulation going.",
    "Go for whole grains! Swap white bread for whole wheat for more fiber.",
    "Eat fermented foods! Yogurt, kimchi, and sauerkraut support gut health.",
    "Use smaller plates to help control portions and avoid overeating.",
    "Try Meatless Monday! A plant-based meal can be delicious and nutritious.",
    "Practice deep breathing to reduce stress and improve focus.",
    "Drink green tea! It’s packed with antioxidants and can boost metabolism.",
    "Keep healthy snacks handy to avoid junk food cravings.",
    "Laugh more! It reduces stress and boosts your immune system.",
    "Eat mindfully! Turn off screens and focus on your food while eating.",
    "Stretch every morning to improve flexibility and circulation.",
    "Choose healthy fats! Avocados, nuts, and olive oil support brain health.",
    "Read food labels! Avoid hidden sugars and artificial ingredients.",
    "Get moving after meals! A short walk aids digestion and stabilizes blood sugar.",
    "Take a digital detox! Unplug for an hour daily to relax and recharge.",
    "Enjoy dark chocolate in moderation—it’s rich in antioxidants!",
    "Plan your meals! It helps with nutrition and prevents last-minute unhealthy choices.",
    "Stand up straight! Good posture improves breathing and confidence.",
    "Eat more omega-3s! Salmon, walnuts, and flaxseeds boost brain function.",
    "Use herbs and spices instead of salt for healthier seasoning.",
    "Try intermittent fasting! It can help with digestion and weight management.",
    "Swap refined carbs for complex ones like quinoa and sweet potatoes.",
    "Get 30 minutes of sunlight daily to boost your vitamin D levels.",
    "Exercise consistently! Aim for at least 150 minutes per week.",
    "Meditate for five minutes daily to reduce stress and improve focus.",
    "Eat slowly and stop when 80% full to prevent overeating.",
    "Try homemade smoothies! They’re nutritious and customizable.",
    "Avoid eating too late—your digestion slows down at night.",
    "Drink a glass of water before meals to help with portion control.",
    "Use a standing desk or take standing breaks while working.",
    "Try batch cooking to have healthy meals ready for busy days.",
    "Take probiotics! They support a healthy gut and digestion.",
    "Get enough magnesium! Nuts, seeds, and leafy greens are great sources.",
    "Try yoga! It improves flexibility, reduces stress, and strengthens muscles.",
    "Swap fried foods for grilled or baked options to cut unhealthy fats.",
    "Eat local and seasonal produce for the freshest and most nutritious options.",
    "Be kind to yourself! A balanced lifestyle includes mental wellness too.",
    "Practice portion control! Use smaller plates to prevent overeating.",
    "Ditch sugary drinks! Opt for herbal teas or black coffee instead.",
    "Eat breakfast like a king, lunch like a prince, and dinner like a pauper!",
    "Take deep breaths before eating to enhance digestion and mindfulness.",
    "Try eating with chopsticks to slow down and savor your meals.",
    "Use olive oil instead of butter for a heart-healthy fat source.",
    "Find an activity you love! Exercise should be enjoyable, not a chore.",
    "Pack healthy snacks when traveling to avoid unhealthy airport food.",
    "Set a screen time limit before bed for better sleep quality.",
    "Try dry brushing! It boosts circulation and exfoliates your skin.",
    "Smile more! A happy mindset improves overall well-being.",
    "Eat before grocery shopping to avoid impulse junk food buys.",
    "Experiment with plant-based proteins like lentils and chickpeas.",
    "Drink lemon water in the morning to kickstart digestion and hydration.",
    "Make homemade salad dressings to cut out preservatives and added sugars.",
    "Include a rainbow of veggies in your meals to get diverse nutrients.",
    "Spend time in nature! It lowers stress and boosts mental health.",
    "Try going dairy-free for a week and see how you feel!",
    "Avoid skipping meals—it leads to cravings and overeating later.",
    "Laugh often! It’s a natural stress reliever and mood booster.",
    "Take your time when eating—your stomach needs time to signal fullness.",
    "Go for a post-lunch walk to boost digestion and energy levels.",
    "Choose whole foods over supplements whenever possible.",
    "Plan your cheat meals in advance to enjoy them guilt-free!",
    "Keep a gratitude journal—it enhances happiness and mindfulness.",
    "Stretch before bed to relax your muscles and improve sleep.",
    "Swap ice cream for frozen yogurt or blended frozen bananas!",
    "Add turmeric to your meals—it’s a powerful anti-inflammatory spice!",
    "Listen to your body! Eat when you're hungry, not when you're bored.",
    "Hydrate with coconut water—it’s a natural electrolyte boost!",
    "Try meal swapping with a friend to explore new healthy recipes!",
    "Make time for hobbies—mental wellness is as important as physical health.",
    "Eat more beans! They’re packed with fiber, protein, and essential nutrients.",
    "Dance more! It’s a fun way to exercise and boost your mood.",
    "Declutter your space—an organized environment reduces stress!",
    "Try a morning jog to kickstart your metabolism and mood.",
    "Choose water-rich foods like watermelon and cucumbers to hydrate naturally.",
    "Challenge yourself to walk 10,000 steps a day for better fitness.",
    "Eat small meals throughout the day to keep energy levels steady.",
    "Take a brisk walk after meals to aid digestion and boost energy.",
    "Go for a hike to enjoy nature and get a full-body workout.",
    "Switch to whole grain pasta for extra fiber and nutrients.",
    "Start every meal with a salad to increase veggie intake.",
    "Try meditation to improve your focus and reduce stress.",
    "Limit artificial sweeteners—they can spike your cravings.",
    "Stretch during breaks to prevent stiffness and improve flexibility.",
    "Dance for 30 minutes to lift your mood and burn calories.",
    "Walk or bike instead of driving for a more active lifestyle.",
    "Start your day with a green smoothie for a vitamin-packed breakfast.",
    "Substitute almond milk for regular milk for a lower-calorie option.",
    "Try a new fitness class this week for fun and variety in your routine.",
    "Treat yourself to a healthy snack when you're craving something sweet.",
    "Opt for a whole grain breakfast instead of sugary cereals.",
    "Start your workout with a warm-up to prevent injuries.",
    "Replace sugar in your coffee with cinnamon for a flavorful twist.",
    "Pick a sport you enjoy to stay active and have fun.",
    "Use a step tracker to monitor your daily movement and stay motivated.",
    "Try stretching before bed for better sleep and muscle recovery.",
    "Snack on Greek yogurt for a boost of protein and probiotics.",
    "Go for a brisk walk during lunch to refresh your body and mind.",
    "Increase your veggie intake by adding them to smoothies or wraps.",
    "Try to limit screen time before bed to improve sleep quality.",
    "Make your own energy bars with oats, nuts, and dried fruit for a healthy snack.",
    "Focus on bodyweight exercises for an easy and effective workout at home.",
    "Opt for grilled or baked chicken instead of fried for a healthier meal.",
    "Make a habit of practicing mindfulness for improved mental clarity.",
    "Take up swimming for a full-body workout with minimal impact on joints.",
    "Substitute white rice for quinoa for extra protein and fiber.",
    "Cut back on salty snacks and opt for air-popped popcorn instead.",
    "Swap regular yogurt for Greek yogurt for a protein boost.",
    "Plan your workouts to stay consistent and track your progress.",
    "Avoid sugary sodas—opt for sparkling water with a splash of lemon.",
    "Try intermittent fasting to reset your digestion and metabolism.",
    "Incorporate resistance training into your routine for stronger muscles.",
    "Include more leafy greens in your meals for a nutrient-dense diet.",
    "Opt for avocado toast instead of buttered toast for a healthier fat source.",
    "Try yoga to improve flexibility, balance, and mental clarity.",
    "Challenge yourself to do 10 push-ups every day for a stronger upper body.",
    "Pack healthy snacks like almonds and apples to avoid fast food temptations.",
    "Snack on hummus and veggies for a satisfying and nutritious treat.",
    "Get creative with homemade smoothies using frozen fruits and greens.",
    "Use chia seeds to boost fiber and omega-3 intake in your meals.",
    "Swap sugary breakfast bars for protein-packed ones made from oats.",
    "Cook meals in bulk for healthy, homemade options throughout the week.",
    "Squeeze lemon on your meals for extra flavor and vitamin C.",
    "Start your morning with a cold shower to boost energy and circulation.",
    "Avoid skipping breakfast to keep your metabolism firing all day.",
    "Incorporate resistance bands into your routine for a low-impact workout.",
    "Switch your favorite snacks for healthier alternatives like fruit or nuts.",
    "Try circuit training for a fun and effective full-body workout.",
    "Add protein to your breakfast with eggs, yogurt, or tofu.",
    "Pick a fun outdoor activity like hiking, biking, or playing sports.",
    "Substitute sour cream with Greek yogurt for a healthier topping.",
    "Make homemade granola with oats, nuts, and honey for a nutritious snack.",
    "Try a food swap—replace your usual bread with lettuce wraps for a lighter meal.",
    "Take a 5-minute walk after dinner to aid digestion and relax.",
    "Add a handful of spinach to your smoothies for an iron boost.",
    "Try a new fruit every week to keep your diet exciting and varied.",
    "Use a food diary to track your meals and identify patterns.",
    "Swap white pasta for zucchini noodles for a low-carb alternative.",
    "Drink herbal teas like chamomile or peppermint to relax before bed.",
    "Add a tablespoon of flaxseeds to your breakfast for omega-3s.",
    "Practice mindful eating by chewing each bite 20-30 times.",
    "Try a new workout playlist to keep your exercise routine fun.",
    "Eat a handful of berries daily for a boost of antioxidants.",
    "Take a 10-minute stretch break during long work sessions.",
    "Swap creamy dressings for vinaigrettes to cut calories.",
    "Try a new spice like paprika or cumin to flavor your meals.",
    "Eat a small handful of almonds for a quick energy boost.",
    "Drink a glass of water with lemon to detoxify your body.",
    "Swap sugary cereals for oatmeal topped with fresh fruit.",
    "Take a yoga class to improve flexibility and reduce stress.",
    "Eat a rainbow of fruits and veggies for a variety of nutrients.",
    "Try a new healthy recipe each week to keep meals exciting.",
    "Swap white rice for cauliflower rice for a low-carb option.",
    "Take a 15-minute walk during your lunch break to refresh.",
    "Add a handful of nuts to your salad for extra crunch and protein.",
    "Try a new type of exercise like Pilates or kickboxing.",
    "Eat a small piece of dark chocolate to satisfy sweet cravings.",
    "Swap soda for sparkling water with a splash of fruit juice.",
];

export default dailyTips;